version: "3"
services:
  redis:
    image: redis:6.0.1
    volumes:
      - "./redis:/data"
  api:
    build:
      context: ./api
      args:
        API_PORT: $API_PORT
    tty: true
    links:
      - mysql
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - PORT=${API_PORT}
      - API_PORT
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET
      - ISSUER
      - AUDIENCE
      - DIGEST_SECRET
      - OPERATOR_NAME
      - OPERATOR_LOGIN_ID
      - OPERATOR_PASSWORD
  client:
    build:
      context: ./client
    tty: true
    ports:
      - "3011:3011"
  operator:
    build: ./operator
    tty: true
    ports:
      - "3012:3012"
    environment:
      VUE_APP_API_ENDPOINT: $API_ENDPOINT
  mysql:
    build: ./mysql
    tty: true
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
  api2:
    build:
      context: ./api
      args:
        API_PORT: 3013
    tty: true
    links:
      - mysql
    ports:
      - "3013:3013"
    environment:
      - PORT=3013
      - API_PORT
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET
      - ISSUER
      - AUDIENCE
      - DIGEST_SECRET
      - OPERATOR_NAME
      - OPERATOR_LOGIN_ID
      - OPERATOR_PASSWORD
