version: '3'
services:
  api:
    build: ./api
    user: "${UID}:${GID}"
    working_dir: "${HOME}"
    tty: true
    volumes:
      - "./api:${HOME}/api"
    ports:
      - "3000:3000"
    command: "node"
  client:
    build: ./client
    user: "${UID}:${GID}"
    working_dir: "${HOME}"
    tty: true
    volumes:
      - "./client:${HOME}/client"
    ports:
      - "3001:3001"
    command: "node"
  operator:
    build: ./operator
    user: "${UID}:${GID}"
    working_dir: "${HOME}"
    tty: true
    volumes:
      - "./operator:${HOME}/operator"
    ports:
      - "3002:3002"
    command: "node"
