version: '3'
services:
  api:
    build: ./api
    working_dir: "/api"
    tty: true
    links:
      - mysql
    volumes:
      - "./api:/api"
    ports:
      - "3010:3000"
    command: "npm run dev"
    environment:
      DB_HOST: 'mysql'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: 'chatservice'
  client:
    build: ./client
    working_dir: "/client"
    tty: true
    volumes:
      - "./client:/client"
    ports:
      - "3011:3001"
    command: "sh ./run.sh"
  operator:
    build: ./operator
    working_dir: "/operator"
    tty: true
    volumes:
      - "./operator:/operator"
    ports:
      - "3012:3002"
    command: "npm run serve"
    environment:
      VUE_APP_API_ENDPOINT: "http://localhost:3010"
  mysql:
    build: ./mysql
    tty: true
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
