version: '3'
services:
  api:
    build: ./api
    tty: true
    links:
      - mysql
    ports:
      - "${API_PORT}:3000"
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET
      - ISSUER
      - AUDIENCE
      - DIGEST_SECRET
  client:
    build: ./client
    tty: true
    ports:
      - "3011:3001"
    environment:
      - API_ENDPOINT
      - API_ENDPOINT_WS
  operator:
    build: ./operator
    tty: true
    ports:
      - "3012:3002"
    environment:
      VUE_APP_API_ENDPOINT: $API_ENDPOINT
  mysql:
    build: ./mysql
    tty: true
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
